spring:
  application:
    name: MovieSystem
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.42.159.228:3306/movie?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf-8&useAffectedRows=true&allowMultiQueries=true
      username: root
      password: Zty200208.
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-prefix: tb_
      logic-delete-field: isdeleted
      logic-not-delete-value: 0
      logic-delete-value: 1
server:
  port: 8080
movieSystem:
  pictureUrl: D:\movie\picture\
  movieUrl: D:\movie\source\